### ISSUE TITLE
Authrefresh crashes randomly at startup

### ISSUE THREAD

**Issue by esumerfd** [xyproto/algernon#121]
With this startup command I am am seeing these stack traces about 1 in 5 times. If I rerun it might work or might fail with a longer stack trace. 

Command executed:

    algernon --server --autorefresh  --cert app/sim/cert.pem  --key app/sim/key.pem  app/sim :3000

```
Server directory:	app/sim
Server address:		:3000
Database:		Bolt (/var/folders/s6/ztxj9rzx6bn4zmczqj627z000000gn/T/algernon.db)
Options:		[Auto-refresh, Server]
Cache mode:		Off
TLS certificate:	app/sim/cert.pem
TLS key:		app/sim/key.pem
Event server:		:5553
Request limit:		10/sec per visitor
Large file threshold:	44040192 bytes
Large file timeout:	10 sec
panic: close of closed channel

goroutine 142 [running]:
github.com/xyproto/symwalk.WalkLimit.func2()
	gopath/pkg/mod/github.com/xyproto/symwalk@v1.1.1/walker.go:78 +0xaf
created by github.com/xyproto/symwalk.WalkLimit
	gopath/pkg/mod/github.com/xyproto/symwalk@v1.1.1/walker.go:75 +0x219
```

This is the longer stack trace if it helps:
```
goroutine 1 [running]:
github.com/xyproto/symwalk.WalkLimit({0xc000044700, 0x34}, 0xc0000120a8, 0x64)
	gopath/pkg/mod/github.com/xyproto/symwalk@v1.1.1/walker.go:115 +0x305
github.com/xyproto/symwalk.Walk(...)
	gopath/pkg/mod/github.com/xyproto/symwalk@v1.1.1/walker.go:26
github.com/xyproto/recwatch.Subfolders({0xc000044700, 0x34})
	gopath/pkg/mod/github.com/xyproto/recwatch@v1.1.0/subfolders.go:21 +0xaa
github.com/xyproto/recwatch.NewRecursiveWatcher({0xc000044700?, 0x2981540?})
	gopath/pkg/mod/github.com/xyproto/recwatch@v1.1.0/recwatch.go:20 +0x25
github.com/xyproto/recwatch.EventServer({0xc000044700, 0x34}, {0x2144bdc, 0x1}, {0x1e5be71, 0x5}, {0x1e5929c, 0x4}, 0x14dc9380)
	opath/pkg/mod/github.com/xyproto/recwatch@v1.1.0/eventserver.go:185 +0xf4
github.com/xyproto/algernon/engine.(*Config).MustServe(0xc000192580, 0xf?)
	gopath/pkg/mod/github.com/xyproto/algernon@v1.14.0/engine/config.go:737 +0x1353
main.main()
	gopath/pkg/mod/github.com/xyproto/algernon@v1.14.0/main.go:32 +0xe5
```

**Comment by xyproto** [comment]
Thanks for reporting!

* Is this on macOS, Linux, FreeBSD or Windows? 
* Is this the latest `main` or release version?

**Comment by xyproto** [comment]
I updated the `symwalk` dependency which had a race issue.

This should now be fixed in `main`. Please re-open this issue if there are still problems with this.
